# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Android Soong build CI

on: [ push ]

jobs:
  download:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: mkdir -p out/soong
    - run: tar xf android12-gsi.tar.xz .
    - run: ls -l
    - run: ./soong_build --top `pwd` --out "out/soong" -n "out" -d "out/soong/build.ninja.d" -l ./Android.bp.list --available_env ./soong.environment.used Android.bp
    - run: ls -l out/soong

    - name: Archive output
      uses: actions/upload-artifact@v3
      with:
        name: modules_deps.json
        path: |
          out/soong/modules_deps.json
