# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Android Soong build CI

on: [ push ]

jobs:
  download:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: ./clone_repo
    - run: tar --exclude="./out/" -cfJ android12-gsi.tar.gz -C aosp .

    - name: Archive repo
      uses: actions/upload-artifact@v3
      with:
        name: android12-gsi
        path: |
          android12-gsi.tar.gz

    - name: Restore Cache android12-gsi.tar.xz
      id: android12-gsi
      uses: actions/cache@v3
      with:
        path: android12-gsi.tar.xz
        key: android12-gsi
        restore-keys: android12-gsi
